### ISSUE TITLE
ValidateSet can not be used for Arrays, PSCredentials, and Hashtable

### ISSUE THREAD

**Issue by ArtWDrahn** [PowerShellOrg/DSC#113]
This error popped up when I was trying to use xNetworking from one of the MS DSC releases. I was wondering why that was the case?  Beyond it existing in this module I can't find any documentation why it needs to be set this way.

**Comment by dlwyatt** [comment]
I asked the same question, and at one point when I was updating Test-cDscResource, I actually tweaked the code to allow ValidateSet to be used on arrays.  (I found other examples of this arrangement existing in WMI / CIM classes, and thought it would be okay.)

Turns out, it doesn't work.  If I remember correctly, you can compile a MOF with this arrangement just fine, but you'll get errors when you try to apply that configuration with the LCM.  So while I don't have any documentation to point you to, I can verify that resources do need to follow that rule.

**Comment by ArtWDrahn** [comment]
Created a pull request documenting this discussion so if anyone else comes through and looks we at least have something going ¯\_(ツ)_/¯ when it comes to this issue.
