### ISSUE TITLE
DSC resources for Team Foundation Server

### ISSUE THREAD

**Issue by jmezach** [PowerShellOrg/DSC#121]
I've written two PowerShell DSC resources for configuring a TFS 2013 Build Controller and a TFS 2015 Build Agent. Perhaps these would be beneficial to others as well. The repository is here:

https://github.com/jmezach/xTeamFoundationServer

**Comment by tysonjhayes** [comment]
Looks pretty awesome. Couple of quick thoughts.

1) Add some pester tests. Some examples of a DSC resource with tests can be found on [xWebAdministration](https://github.com/PowerShell/xWebAdministration/tree/dev/Tests) basically proving to anyone who takes the code that it works as expected.
2) If you are doing an Add-Type check to make sure you haven't loaded the type previously, in my experience it leads to errors being thrown. This will typically come up in testing the code.
3) IMO you probably shouldn't be assuming the path for the agent download like you do in xTeamAgent. Instead of giving a ServerURI and then adding the path in code I'd suggest asking for the full path or having some logic around trying known good paths.

**Comment by jmezach** [comment]
Thanks for the suggestions. I'll look into writing some tests when I've got the time ;).

As for the agent download; I think the URL I'm using right now is in fact an API, so I doubt if it will change much and by doing it this way it makes it a little bit easier to use because you only need to know the URL of your TFS server. Perhaps I could add an optional parameter that defaults to the current relative URL, but can be overriden if it ever changes. Would that work?

**Comment by tysonjhayes** [comment]
In my experience with DSC the more specific the better. So if you want to allow an override don't force a specific path but force the user to provide the path to you. Just my thoughts I haven't actually used this before so I have no idea if the suggestion even makes sense. :grin:

**Comment by usepowershell** [comment]
@jmezach You want to host that repo under PowerShellOrg?  I can set up a repo and get you commit rights to it.  I'd request that you get rid of that "x" prefix on the resource names.  It'd be a better route to  namespace the resource names like jmezach_TFSBuildAgent and just use a friendly name of TFSBuildAgent.

**Comment by jmezach** [comment]
That would be nice yes. Not sure what you mean with the naming of these things though. I thought that the x prefix was sort of a convention? Or is that just for the name of the module and not the name of the resources themselves?

**Comment by usepowershell** [comment]
@jmezach 'x' and 'c' were attempts at namespacing where the resource came from (x was microsoft's experimental resources - e.g. unsupported, and c was the community variant since MS couldn't take community contributions).  It was annoying, but needed given the way the PowerShell team had to release resources at the onset.  It is pointless and counterproductive now, as we try to streamline naming.

**Comment by usepowershell** [comment]
Repo created https://github.com/PowerShellOrg/TeamFoundationServer and I invited you to join a group to manage it @jmezach
